import colors from "tailwindcss/colors";

module.exports = {
  theme: {
    extend: {
      colors: {
        transparent: "transparent",
        current: "currentColor",

        emerald: colors.emerald,
        customGreen: {
          DEFAULT: "#3ba23f",
          dark: "#39913c",
        },
        customRed: {
          DEFAULT: "#c91f3b",
        },
      },
    },
  },
  variants: {
    extend: {},
  },
  content: [
    "content/**/*.md",
    "components/**/*.{vue,js,ts}",
    "layouts/**/*.vue",
    "pages/**/*.vue",
    "composables/**/*.{js,ts}",
    "plugins/**/*.{js,ts}",
    "App.{js,ts,vue}",
    "app.{js,ts,vue}",
    "Error.{js,ts,vue}",
    "error.{js,ts,vue}",
    "content/**/*.md",
  ],
  safelist: [
    "bg-customGreen",
    "bg-customGreen-dark",
    "bg-customRed",
    "text-customGreen",
    "text-customGreen-dark",
    "text-customRed",
    "bg-rose-600",
    "bg-gray-100",
    "bg-gray-200",
    "bg-gray-400",
    "text-gray-900",
    "text-gray-800",
    "from-yellow-500",
    "to-yellow-500",
    "from-yellow-700",
    "to-yellow-700",
    "from-gray-700",
    "to-gray-700",
    "from-red-500",
    "to-red-500",
    "from-indigo-700",
    "to-indigo-700",
    "to-indigo-500",
    "from-red-700",
    "to-red-700",
    "from-teal-700",
    "to-teal-700",
    "from-teal-500",
    "to-teal-500",
    "to-teal-600",
    "text-rose-600",
    "py-24",
    "bg-emerald-900",
    "bg-emerald-700",
    "bg-yellow-600",
    "bg-green-700",
    "text-green-700",
    "bg-red-700",
    "text-red-700",
    "bg-yellow-200",
    "text-yellow-200",
    "bg-emerald-800",
  ],
  plugins: [],
  content: [
    "./components/**/*.{vue,js}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
  ],
};
